branches:
  only:
    - master

os: Visual Studio 2017

clone_depth: 1

install:
  - mkdir ext && cd ext
  - git clone git://github.com/objectcomputing/OpenDDS.git
  - cd OpenDDS
  - git fetch && git fetch --tags
  - git checkout tags/DDS-3.13.2 
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" amd64  
  - ps: Start-FileDownload 'http://download.ociweb.com/TAO-2.2a/ACE+TAO-2.2a_with_latest_patches_NO_makefiles.zip'
  - 7z x ACE+TAO-2.2a_with_latest_patches_NO_makefiles.zip
  - set MPC_ROOT C:\projects\openddsharp\ext\OpenDDS\ACE_wrappers\MPC
  - set ACE_ROOT C:\projects\openddsharp\ext\OpenDDS\ACE_wrappers
  - set TAO_ROOT C:\projects\openddsharp\ext\OpenDDS\ACE_wrappers\TAO
  - set DDS_ROOT C:\projects\openddsharp\ext\OpenDDS
  - set PATH=%PATH%;C:\projects\openddsharp\ext\OpenDDS\ACE_wrappers\bin;C:\projects\openddsharp\ext\OpenDDS\bin;C:\projects\openddsharp\ext\OpenDDS\ACE_wrappers\lib;C:\projects\openddsharp\ext\OpenDDS\lib  
  - call configure --no-tests  
  - git apply C:\projects\openddsharp\Patches\ConditionImpl.h.patch
  - git apply C:\projects\openddsharp\Patches\DataReaderImpl.cpp.patch
  - git apply C:\projects\openddsharp\Patches\DataReaderImpl.h.patch
  - git apply C:\projects\openddsharp\Patches\unique_ptr.h.patch  
  - msbuild DDS_TAOv2.sln /m /p:Configuration=Debug;Platform=x64
  - xcopy C:\projects\openddsharp\ext\OpenDDS\ACE_wrappers\lib\* C:\projects\openddsharp\ext\OpenDDS\ACE_wrappers\lib_x64 /s /i
  - xcopy C:\projects\openddsharp\ext\OpenDDS\ACE_wrappers\bin\* C:\projects\openddsharp\ext\OpenDDS\ACE_wrappers\bin_x64 /s /i
  - xcopy C:\projects\openddsharp\ext\OpenDDS\lib\* C:\projects\openddsharp\ext\OpenDDS\lib_x64 /s /i
  - xcopy C:\projects\openddsharp\ext\OpenDDS\bin\* C:\projects\openddsharp\ext\OpenDDS\bin_x64 /s /i
  - xcopy C:\projects\openddsharp\OpenDDSharp\OpenDDSharp.IdlGenerator\HeaderTemplate.txt %DDS_ROOT%\dds\idl
  - xcopy C:\projects\openddsharp\OpenDDSharp\OpenDDSharp.IdlGenerator\ImplTemplate.txt %DDS_ROOT%\dds\idl
  - msbuild C:\projects\openddsharp\OpenDDSharp\OpenDDSharp.sln /t:OpenDDSharp_ExportFileGenerator /p:Configuration="Release" /p:Platform="Any CPU" /p:BuildProjectReferences=false
  - xcopy C:\projects\openddsharp\OpenDDSharp\OpenDDSharp.ExportFileGenerator\bin\Release\* %ACE_ROOT%\bin
  - nuget restore C:\projects\openddsharp\OpenDDSharp\OpenDDSharp.sln
  - cd ..\..
  
platform:
  - x64

configuration:
  - Debug

build_script:
  - msbuild C:\projects\openddsharp\OpenDDSharp\OpenDDSharp.sln /m /p:Configuration=Debug;Platform=x64

test:
  assemblies:
    only:
      - OpenDDSharp.UnitTest.dll
  
